
# whether to calculate diagnostics from scratch, deleting old files
from_scratch: true

# whether to compute for each tracer
all: false
density: false
halo: false
galaxy: false
ngc: false
sgc: false
mtng: false
simbig: false

# number of threads for P(k) computation
threads: -1  # -1 for all available threads

# whether to compute summaries on a high resolution grid (~ 4 Mpc/h)
high_res: true

# whether to use NGP meshing (forces high_res to false)
use_ngp: false

# whether to focus summaries at a specific redshift
focus_z: null  # redshift to focus on (null for all redshifts)

# which summaries to run
summaries:
    - nz             # n(z)
    - Pk             # power spectrum
    # - TwoPCF         # two-point correlation function
    # - KNN            # k-nearest neighbors
    # - WST            # wavelet scattering transform
    - Bk             # bispectrum
    # - Density Split  # density split statistics

# TODO: merge these?
survey_backend: pypower  # backend for survey computations (pylians or pypower)
bispectrum_backend: polybin # backend for bispectrum computations (bfast or polybin)

# whether to use abundance matching to affix number density
halo_density: 1e-4  # number density in h^3/Mpc^3. null for no abundance matching
halo_proxy: mass  # property for abundance matching (null for no abundance matching)

# Note, we don't have a mass proxy for galaxies, so we can't use abundance matching
galaxy_density: null  # number density in h^3/Mpc^3. null for no abundance matching
galaxy_proxy: null  # property for abundance matching (null for no abundance matching)
