#PBS -N borg2lpt
#PBS -q batch
#PBS -l walltime=4:00:00
#PBS -l nodes=1:ppn=128,mem=256gb
#PBS -t 1-100
#PBS -j oe
#PBS -o ${HOME}/data/jobout/${PBS_JOBNAME}.${PBS_JOBID}.o

echo cd-ing...

cd /home/mattho/git/cmass-ili/

echo activating environment...
module restore myborg
source /home/mattho/data/venv/borg/bin/activate

echo running script...
echo "arrayind is ${PBS_ARRAYID}"

python ./scripts_simulation/run_borg-quijote.py --cind ${PBS_ARRAYID}

echo done.