#PBS -N fit_bias
#PBS -q batch
#PBS -l walltime=4:00:00
#PBS -l nodes=1:ppn=64,mem=128gb
#PBS -t 1300-1999
#PBS -j oe
#PBS -o ./data/logs/_temp.o

echo cd-ing...

cd /home/mattho/git/ltu-cmass

echo activating environment...
module restore cmass
source ~/.bashrc
conda activate cmass-env

echo running script...
echo "arrayind is ${PBS_ARRAYID}"

python -m cmass.bias.fit_halo_bias --lhid ${PBS_ARRAYID}

echo done