#PBS -N pmwd
#PBS -q batch
#PBS -l walltime=4:00:00
#PBS -l nodes=1:ppn=64,mem=128gb
#PBS -t 0-3
#PBS -j oe
#PBS -o ./data/logs/_temp.o

echo cd-ing...

cd /home/mattho/git/cmass-ili/

echo activating environment...
module load gcc/13.2.0 openmpi/4.1.2-intel
source ~/.bashrc
conda activate cmass-env

echo running script...
echo "arrayind is ${PBS_ARRAYID}"

python -m cmass.nbody.pmwd --lhid ${PBS_ARRAYID} --matchIC

echo done