#PBS -N remap
#PBS -q batch
#PBS -l walltime=4:00:00
#PBS -l nodes=1:has1gpu:ppn=40,mem=128gb
#PBS -t 0,2,3
#PBS -j oe
#PBS -o ./data/logs/_temp.o

echo cd-ing...

cd /home/mattho/git/cmass-ili/

echo activating environment...
module load cuda
source /data80/mattho/anaconda3/bin/activate
conda activate jax

echo running script...
echo "arrayind is ${PBS_ARRAYID}"

python -m cmass_ili.survey.remap_as_cuboid --lhid ${PBS_ARRAYID} --simtype jaxlpt-quijote

echo done