#PBS -N cmassFM
#PBS -q batch
#PBS -l walltime=4:00:00
#PBS -l nodes=1:ppn=40,mem=128gb
#PBS -t 0,3
#PBS -j oe
#PBS -o ./data/logs/_temp.o

echo cd-ing...

cd /home/mattho/git/cmass-ili/

echo activating environment...
source /data80/mattho/anaconda3/bin/activate
conda activate jax

echo running script...
echo "arrayind is ${PBS_ARRAYID}"

python ./simulation/rho_to_halo.py --lhid ${PBS_ARRAYID} --simtype pmwd-quijote

echo done