
save_dir: null  # where to save trained models (default e.g. wdir/quijotelike/fastpm/models)

# ~~ GLOBAL ARGS ~~
exp_index: null  # index of experiment to run (null for all)
net_index: 0     # index of network to use in cfg.net
device: cpu  # cpu or cuda

# ~~ EXPERIMENT ARGS ~~
Nmax: -1  # maximum number of simulations to load (-1 for all)

correct_shot: true  # whether to correct for shot noise when normalizing

halo: True      # whether to train on halo summaries
galaxy: False    # whether to train on galaxy summaries
ngc_lightcone: False # whether to train on ngc_lightcone summaries
sgc_lightcone: False # whether to train on sgc_lightcone summaries
mtng_lightcone: False # whether to train on mtng_lightcone summaries
simbig_lightcone: False # whether to train on simbig_lightcone summaries

experiments:
  - summary: [Pk0]   # monopole
    kmin: [0., 0.02]
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]
  - summary: [Pk0, Pk2, Pk4]   # monopole, quadrupole, hexadecapole
    kmin: [0., 0.02]
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]
  - summary: [Pk0, Pk2, Pk4, Bk0]   # monopole, quadrupole, hexadecapole, reduced bispectrum
    kmin: [0.,0.02]
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]
  - summary: [Pk0, Pk2, Pk4, Qk0]   # monopole, quadrupole, hexadecapole, reduced bispectrum
    kmin: [0.,0.02]
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]
  - summary: [zPk0]   # z-space monopole
    kmin: [0.,0.02]
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]
  - summary: [zPk0, zPk2, zPk4]  # z-space monopole, quadrupole, hexadecapole
    kmin: [0.,0.02]
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]
  - summary: [zPk0, zPk2, zPk4, zBk0]   # monopole, quadrupole, hexadecapole, reduced bispectrum
    kmin: [0.,0.02]
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]
  - summary: [zPk0, zPk2, zPk4, zQk0]   # monopole, quadrupole, hexadecapole, reduced bispectrum
    kmin: [0.,0.02]
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]
  - summary: [zPk0, zPk2, zPk4, zEqBk0]   # monopole, quadrupole, hexadecapole, reduced bispectrum
    kmin: [0.,0.02]
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]
  - summary: [zPk0, zPk2, zPk4, zEqQk0]   # monopole, quadrupole, hexadecapole, reduced equilateral bispectrum
    kmin: [0.,0.02]
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]

# ~~ TRAINING ARGS ~~
Nnets: 10  # number of best networks to ensemble

val_frac: 0.1  # fraction of data to use for validation
test_frac: 0.1  # fraction of data to use for testing
seed: 0  # random seed for train/val/test split
include_hod: True  # whether to infer HOD parameters
include_noise: False  # whether to infer noise parameters

prior: quijote  # prior to use for training (uniform, quijote)
backend: lampe # backend to use for training (sbi/lampe/pydelfi)
engine: NPE    # engine to use for training (NPE/NLE/NRE)

batch_size: null  # batch size
learning_rate: null  # learning rate
stop_after_epochs: 50  # stop early after this many epochs
weight_decay: 0  # weight decay
lr_decay_factor: 0.5  # learning rate decay factor
lr_patience: 10  # learning rate decay patience
