# North galactic cap CMASS survey
geometry: ngc

# Data augmentation seed (for random rotations)
aug_seed: 0

# # Additional ra, dec, z cuts
# ra_range: [150, 220]
# dec_range: [20, 60]
z_range: [0.4, 0.7]

# For lightcone extrapolation
boss_dir: "${meta.wdir}/obs/"  # path to observational masks
fix_nz: False

# For randoms creation only (will not load any correct data!)
randoms: False

# For turning off all masking (only for testing footprint coverage!)
nomask: False
